# Generated by Django 4.1.1 on 2022-09-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='urlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longURL', models.CharField(max_length=255)),
                ('shortURL', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
