apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  type: {{.Values.serviceType }} 
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
      nodePort: {{ .Values.nodePort }}