apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: frontend
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: ahmedsalahucf/urlshortner-frontend:latest
        ports:
        - containerPort: 800
        env:
        - name: NODE_ENV
          value: production
        - name: REACT_APP_BACKEND_ADDRESS
          valueFrom: 
            configMapKeyRef:
              name: react-configmap
              key: backend_address
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: frontend
spec:
  selector:
    app: react
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 800
      targetPort: 800
      nodePort: 30000