from django.db import models

class urlShortener(models.Model):
    # longURL stores the long URL submitted by the user 
    longURL = models.CharField(max_length=255)
    # shortURL stores the short URL equivalent of the long URL generated by the server
    shortURL = models.CharField(max_length=10)

    def __str__(self):
        return self.shortURL